
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LESS_TE = 30;
  public static final int PARENTESIS_CIERRE = 38;
  public static final int CHAR = 12;
  public static final int EMPTY = 24;
  public static final int ENTERO = 5;
  public static final int CERRAR_BLOQUE = 35;
  public static final int CASE = 16;
  public static final int DIVISION_ENTERA = 58;
  public static final int RESTA = 48;
  public static final int EXPONENCIAL = 9;
  public static final int DOS_PUNTOS = 46;
  public static final int INT = 57;
  public static final int SEPARADOR = 44;
  public static final int NOT = 55;
  public static final int AND = 53;
  public static final int CARACTER = 4;
  public static final int FRACCION = 7;
  public static final int OR = 54;
  public static final int FIN_SENTENCIA = 43;
  public static final int BOOL = 8;
  public static final int INCREMENTO = 41;
  public static final int SUMA = 47;
  public static final int MAIN = 56;
  public static final int ABRIR_PARENTESIS_CUADRADO = 39;
  public static final int IF = 13;
  public static final int ID = 2;
  public static final int ABRIR_BLOQUE = 34;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int EQUAL = 27;
  public static final int GREATHER_TE = 32;
  public static final int TRUE = 22;
  public static final int DECREMENTO = 42;
  public static final int error = 1;
  public static final int COMA = 45;
  public static final int CADENA = 3;
  public static final int MODULO = 52;
  public static final int CIN = 20;
  public static final int BREAK = 19;
  public static final int ERROR = 33;
  public static final int ASIGNACION = 36;
  public static final int SWITCH = 15;
  public static final int CERRAR_PARENTESIS_CUADRADO = 40;
  public static final int POTENCIA = 51;
  public static final int ELSE = 14;
  public static final int COUT = 21;
  public static final int N_EQUAL = 28;
  public static final int WHILE = 26;
  public static final int DEFAULT = 17;
  public static final int FLOAT = 10;
  public static final int GREATHER_T = 31;
  public static final int STRING = 11;
  public static final int PARENTESIS_APERTURA = 37;
  public static final int FALSE = 23;
  public static final int DIVISION = 50;
  public static final int LESS_T = 29;
  public static final int FLOTANTE = 6;
  public static final int DO = 25;
  public static final int MULTIPLICACION = 49;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "CADENA",
  "CARACTER",
  "ENTERO",
  "FLOTANTE",
  "FRACCION",
  "BOOL",
  "EXPONENCIAL",
  "FLOAT",
  "STRING",
  "CHAR",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "RETURN",
  "BREAK",
  "CIN",
  "COUT",
  "TRUE",
  "FALSE",
  "EMPTY",
  "DO",
  "WHILE",
  "EQUAL",
  "N_EQUAL",
  "LESS_T",
  "LESS_TE",
  "GREATHER_T",
  "GREATHER_TE",
  "ERROR",
  "ABRIR_BLOQUE",
  "CERRAR_BLOQUE",
  "ASIGNACION",
  "PARENTESIS_APERTURA",
  "PARENTESIS_CIERRE",
  "ABRIR_PARENTESIS_CUADRADO",
  "CERRAR_PARENTESIS_CUADRADO",
  "INCREMENTO",
  "DECREMENTO",
  "FIN_SENTENCIA",
  "SEPARADOR",
  "COMA",
  "DOS_PUNTOS",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "POTENCIA",
  "MODULO",
  "AND",
  "OR",
  "NOT",
  "MAIN",
  "INT",
  "DIVISION_ENTERA"
  };
}

